
-- sqlite> .read dice.sql

-- create table for dices 
CREATE TABLE DICE(
   NAME CHAR(50) NOT NULL,
   VALUE INT NOT NULL,
   SIDE INT NOT NULL,
   PRIMARY KEY (NAME, SIDE)	
);

-- initialize the values of dices 
INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('A', 1, 2);

INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('A', 2, 4);

INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('A', 3, 9);

INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('B', 1, 1);

INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('B', 2, 6);

INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('B', 3, 8);

INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('C', 1, 3);

INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('C', 2, 5);

INSERT INTO DICE(NAME, SIDE, VALUE)
VALUES ('C', 3, 8);

-- Queries for all combinations of dices 
CREATE TABLE WIN_COMBO AS 
SELECT d1.NAME AS d1_name, d2.NAME AS d2_name, SUM(d1.value > d2.value) *100 
		/ (SELECT COUNT(d1.NAME == 'A') FROM DICE d1 JOIN DICE d2 ON d1.NAME != d2.NAME GROUP BY d1.NAME, d2.NAME) as win_percent
FROM DICE d1 JOIN DICE d2 ON d1.NAME < d2.NAME
GROUP BY d1.NAME, d2.NAME;

SELECT *
FROM WIN_COMBO

